___

# <font color= #6A994E> **Análisis de Contenido de Noticias** </font>
#### <font> `PAP Movilidad Urbana Sustentable`</font>
<Strong> Oscar Josué Rocha & Viviana Toledo </Strong>

_13/09/2026._

___

# <font color= #6A994E> **Librerías & Datos** </font>

In [ ]:
import pandas as pd

In [ ]:
news2020 = pd.read_csv('./data/interim/MiBici_2020.csv', encoding='utf-8') 
news2021 = pd.read_csv('./data/interim/MiBici_2021.csv', encoding='utf-8')
news2022 = pd.read_csv('./data/interim/MiBici_2022.csv', encoding='utf-8')
news2023 = pd.read_csv('./data/interim/MiBici_2023.csv', encoding='utf-8')
news2024 = pd.read_csv('./data/interim/MiBici_2024.csv', encoding='utf-8')
news2025 = pd.read_csv('./data/interim/MiBici_2025.csv', encoding='utf-8')
news2026 = pd.read_csv('./data/interim/MiBici2026.csv', encoding='utf-8')

# <font color= #6A994E> **Análisis Exploratorio de Datos** </font>

In [5]:
# Encontrar el medio más repetido
def top_medios(df):
    top2 = df['medio'].value_counts().iloc[:2]

    for index_val, count in top2.items():
        print(f"{index_val}: {count}")

# Noticias con corpus
#def corpus_count(df):

In [6]:
news2020['texto'].value_counts()

texto
While we can fix your team, we unfortunately can’t do much about this non-existent page. Visit the menu above or the links below to keep exploring.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   26
Derechos Reservados - Notisistema 2018 |Defensoría de Audiencia|Aviso de Privacidad\n\nNotisistema utiliza cookies para ofrecerte una mejor experiencia de navegación y entrega de publicidad. Al navegar en nuestro sitio aceptas las cookies que utilizamos.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        14

In [8]:
top_medios(news2020)

Mural: 30
El Informador: 26

In [10]:
news2020

,medio,fecha,titulo,nivel,estado,chars,segundos,url_final,error,texto
0,El Informador,30/12/2020,"En el abandono, un tramo del parque lineal Pat...",trafilatura,trafilatura,11437,0.78,https://www.informador.mx/En-el-abandono-un-tr...,NaN,"En el abandono, un tramo del parque lineal Pat..."
1,Lider 919,28/12/2020,Este año fallecieron 13 ciclistas en el AMG,error,error,0,5.23,https://lider919.com/este-ano-fallecieron-13-c...,HTTP 404,NaN
2,Milenio,27/12/2020,"Desde temprano, tapatíos pasan un rato agradab...",trafilatura,trafilatura,1602,0.56,https://www.milenio.com/politica/comunidad/gua...,NaN,Como todos los domingos desde que se reanudaro...
3,Notisistema,16/12/2020,El mal estado de la ciclovía en avenida México,playwright,playwright,252,6.38,https://www.notisistema.com/noticias/el-mal-es...,HTTP 404,Derechos Reservados - Notisistema 2018 |Defens...
4,NTR Guadalajara,14/12/2020,Desaparecen bolardos en Ávila Camacho,trafilatura,trafilatura,877,0.44,https://www.ntrguadalajara.com/post.php?id_not...,NaN,Al menos 30 bolardos que dividían la avenida Á...
...,...,...,...,...,...,...,...,...,...,...
191,Mural,18/05/2020,Instalará Zapopan ciclovías emergentes ante co...,playwright,playwright,147,5.85,https://www.mural.co/instalara-zapopan-ciclovi...,HTTP 404,"While we can fix your team, we unfortunately c..."
192,Mural,18/05/2020,Va al 94% renovación de ciclovía en Federalismo,playwright,playwright,147,9.45,https://www.mural.co/va-al-94-renovacion-de-ci...,HTTP 404,"While we can fix your team, we unfortunately c..."
193,El Informador,18/05/2020,Muere ciclista tras ser arrollado en Periféric...,trafilatura,trafilatura,1612,0.16,https://www.informador.mx/jalisco/Muere-ciclis...,NaN,Muere ciclista tras ser arrollado en PerifÃ©ri...
194,NTR Guadalajara,04/05/2020,"Renovación de ciclovía, con 90% de avance",trafilatura,trafilatura,1789,2.23,https://www.ntrguadalajara.com/post.php?id_not...,NaN,Las obras de remodelación de la ciclovía de Fe...
195,Mural,01/04/2020,Llegan 450 bicicletas para MiBici,playwright,playwright,147,8.06,https://www.mural.co/llegan-450-bicicletas-par...,HTTP 404,"While we can fix your team, we unfortunately c..."

In [11]:
news2020['texto']

0      En el abandono, un tramo del parque lineal Pat...
1                                                    NaN
2      Como todos los domingos desde que se reanudaro...
3      Derechos Reservados - Notisistema 2018 |Defens...
4      Al menos 30 bolardos que dividían la avenida Á...
                             ...
191    While we can fix your team, we unfortunately c...
192    While we can fix your team, we unfortunately c...
193    Muere ciclista tras ser arrollado en PerifÃ©ri...
194    Las obras de remodelación de la ciclovía de Fe...
195    While we can fix your team, we unfortunately c...
Name: texto, Length: 196, dtype: object

In [23]:
news2020['error']

0           NaN
1      HTTP 404
2           NaN
3      HTTP 404
4           NaN
         ...
191    HTTP 404
192    HTTP 404
193         NaN
194         NaN
195    HTTP 404
Name: error, Length: 196, dtype: object

In [18]:
news2020[news2020['error'].isin(news2020['error'].value_counts().index)]

,medio,fecha,titulo,nivel,estado,chars,segundos,url_final,error,texto
1,Lider 919,28/12/2020,Este año fallecieron 13 ciclistas en el AMG,error,error,0,5.23,https://lider919.com/este-ano-fallecieron-13-c...,HTTP 404,NaN
3,Notisistema,16/12/2020,El mal estado de la ciclovía en avenida México,playwright,playwright,252,6.38,https://www.notisistema.com/noticias/el-mal-es...,HTTP 404,Derechos Reservados - Notisistema 2018 |Defens...
5,Notisistema,09/12/2020,Instalan material antiderrapante en ciclovía d...,playwright,playwright,252,5.49,https://www.notisistema.com/noticias/instalan-...,HTTP 404,Derechos Reservados - Notisistema 2018 |Defens...
8,Lider 919,01/12/2020,"Por obras públicas, cerrarán durante cuatro me...",error,error,0,3.93,https://lider919.com/por-obras-publicas-cerrar...,HTTP 404,NaN
12,UDGTV,29/11/2020,No se acatan medidas sanitarias en Vía RecreAc...,playwright,playwright,113,5.53,https://udgtv.com/noticias/no-se-acatan-medida...,HTTP 404,No se pudo encontrar la página solicitada. Est...
...,...,...,...,...,...,...,...,...,...,...
187,Lider 919,22/05/2020,Piden habilitar red de ciclovías emergentes co...,error,error,0,4.06,https://lider919.com/piden-habilitar-red-de-ci...,HTTP 404,NaN
188,Mural,21/05/2020,Habilitará Zapopan 3 ciclovías emergentes,playwright,playwright,147,13.70,https://www.mural.co/habilitara-zapopan-3-cicl...,HTTP 404,"While we can fix your team, we unfortunately c..."
191,Mural,18/05/2020,Instalará Zapopan ciclovías emergentes ante co...,playwright,playwright,147,5.85,https://www.mural.co/instalara-zapopan-ciclovi...,HTTP 404,"While we can fix your team, we unfortunately c..."
192,Mural,18/05/2020,Va al 94% renovación de ciclovía en Federalismo,playwright,playwright,147,9.45,https://www.mural.co/va-al-94-renovacion-de-ci...,HTTP 404,"While we can fix your team, we unfortunately c..."
195,Mural,01/04/2020,Llegan 450 bicicletas para MiBici,playwright,playwright,147,8.06,https://www.mural.co/llegan-450-bicicletas-par...,HTTP 404,"While we can fix your team, we unfortunately c..."

In [50]:
clean_2020=news2020[news2020['error'].isna()]
clean_2020.to_csv("./data/interim/clean_2020.csv")

In [51]:
clean_2020

,medio,fecha,titulo,nivel,estado,chars,segundos,url_final,error,texto
0,El Informador,30/12/2020,"En el abandono, un tramo del parque lineal Pat...",trafilatura,trafilatura,11437,0.78,https://www.informador.mx/En-el-abandono-un-tr...,NaN,"En el abandono, un tramo del parque lineal Pat..."
2,Milenio,27/12/2020,"Desde temprano, tapatíos pasan un rato agradab...",trafilatura,trafilatura,1602,0.56,https://www.milenio.com/politica/comunidad/gua...,NaN,Como todos los domingos desde que se reanudaro...
4,NTR Guadalajara,14/12/2020,Desaparecen bolardos en Ávila Camacho,trafilatura,trafilatura,877,0.44,https://www.ntrguadalajara.com/post.php?id_not...,NaN,Al menos 30 bolardos que dividían la avenida Á...
6,El Informador,07/12/2020,Acaban con bolardos en ciclovía de Avenida México,trafilatura,trafilatura,2036,0.17,https://www.informador.mx/jalisco/Acaban-con-b...,NaN,Acaban con bolardos en ciclovÃa de Avenida MÃ©...
7,Trafico ZMG,01/12/2020,Anuncian cierre vial en Mariano Otero por cons...,trafilatura,trafilatura,1391,1.08,https://traficozmg.com/2020/12/anuncian-cierre...,NaN,Anuncian cierre vial en Mariano Otero por cons...
...,...,...,...,...,...,...,...,...,...,...
185,NTR Guadalajara,26/05/2020,Ampliará GDL 13 km de ciclovías por coronavirus,trafilatura,trafilatura,1917,0.41,https://www.ntrguadalajara.com/post.php?id_not...,NaN,Como parte de las medidas de regreso a la nuev...
189,El Informador,20/05/2020,Inician obra de ciclovía emergente en Avenid...,trafilatura,trafilatura,1808,0.18,https://www.informador.mx/jalisco/Inician-obra...,NaN,Inician obra de ciclovÃa âemergenteâ en Avenid...
190,El Informador,19/05/2020,Disminuyen traslados de Mi Bici durante la pan...,trafilatura,trafilatura,1798,0.27,https://www.informador.mx/jalisco/Disminuyen-t...,NaN,Disminuyen traslados de Mi Bici durante la pan...
193,El Informador,18/05/2020,Muere ciclista tras ser arrollado en Periféric...,trafilatura,trafilatura,1612,0.16,https://www.informador.mx/jalisco/Muere-ciclis...,NaN,Muere ciclista tras ser arrollado en PerifÃ©ri...
194,NTR Guadalajara,04/05/2020,"Renovación de ciclovía, con 90% de avance",trafilatura,trafilatura,1789,2.23,https://www.ntrguadalajara.com/post.php?id_not...,NaN,Las obras de remodelación de la ciclovía de Fe...

In [ ]:
error_2020=news2020[news2020['error'].notna()]
error_2020

,medio,fecha,titulo,nivel,estado,chars,segundos,url_final,error,texto
1,Lider 919,28/12/2020,Este año fallecieron 13 ciclistas en el AMG,error,error,0,5.23,https://lider919.com/este-ano-fallecieron-13-c...,HTTP 404,NaN
3,Notisistema,16/12/2020,El mal estado de la ciclovía en avenida México,playwright,playwright,252,6.38,https://www.notisistema.com/noticias/el-mal-es...,HTTP 404,Derechos Reservados - Notisistema 2018 |Defens...
5,Notisistema,09/12/2020,Instalan material antiderrapante en ciclovía d...,playwright,playwright,252,5.49,https://www.notisistema.com/noticias/instalan-...,HTTP 404,Derechos Reservados - Notisistema 2018 |Defens...
8,Lider 919,01/12/2020,"Por obras públicas, cerrarán durante cuatro me...",error,error,0,3.93,https://lider919.com/por-obras-publicas-cerrar...,HTTP 404,NaN
12,UDGTV,29/11/2020,No se acatan medidas sanitarias en Vía RecreAc...,playwright,playwright,113,5.53,https://udgtv.com/noticias/no-se-acatan-medida...,HTTP 404,No se pudo encontrar la página solicitada. Est...
...,...,...,...,...,...,...,...,...,...,...
187,Lider 919,22/05/2020,Piden habilitar red de ciclovías emergentes co...,error,error,0,4.06,https://lider919.com/piden-habilitar-red-de-ci...,HTTP 404,NaN
188,Mural,21/05/2020,Habilitará Zapopan 3 ciclovías emergentes,playwright,playwright,147,13.70,https://www.mural.co/habilitara-zapopan-3-cicl...,HTTP 404,"While we can fix your team, we unfortunately c..."
191,Mural,18/05/2020,Instalará Zapopan ciclovías emergentes ante co...,playwright,playwright,147,5.85,https://www.mural.co/instalara-zapopan-ciclovi...,HTTP 404,"While we can fix your team, we unfortunately c..."
192,Mural,18/05/2020,Va al 94% renovación de ciclovía en Federalismo,playwright,playwright,147,9.45,https://www.mural.co/va-al-94-renovacion-de-ci...,HTTP 404,"While we can fix your team, we unfortunately c..."
195,Mural,01/04/2020,Llegan 450 bicicletas para MiBici,playwright,playwright,147,8.06,https://www.mural.co/llegan-450-bicicletas-par...,HTTP 404,"While we can fix your team, we unfortunately c..."

In [38]:
error_2020['medio'].value_counts()

medio
Mural              27
Lider 919          15
Notisistema        14
UDGTV              11
Cronica Jalisco     5
Reporte indigo      1
Meganoticias        1
Telediario          1
Name: count, dtype: int64

In [52]:
def cleaning(df,year):

    clean_df=df[df['error'].isna()]
    return clean_df.to_csv(f"./data/clean/clean_{year}.csv")

    
dfs= [news2020, news2021, news2022, news2023, news2024, news2025, news2026]
year=2020
for df in dfs:
    cleaning(df,year)
    year+=1

## <font color= #A7C957> **Heading 2** </font>

### <font color= #ECF39E> &nbsp; **RAW** </font>